# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Burja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('json_data', models.TextField(blank=True, null=True)),
                ('original_data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BurjaZnaki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('json_data', models.TextField(blank=True, null=True)),
                ('original_data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Counters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('json_data', models.TextField(blank=True, null=True)),
                ('original_data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('json_data', models.TextField(blank=True, null=True)),
                ('original_data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ParkiriscaLPT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('json_data', models.TextField(blank=True, null=True)),
                ('original_data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Prikljucki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('json_data', models.TextField(blank=True, null=True)),
                ('original_data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Razcepi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('json_data', models.TextField(blank=True, null=True)),
                ('original_data', models.TextField()),
            ],
        ),
    ]
