# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-14 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prometapi', '0002_cameras'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('json_data', models.TextField(blank=True, null=True)),
                ('original_data', models.TextField()),
            ],
        ),
    ]
